#! /bin/sh
### BEGIN INIT INFO
# Provides: noip
# Required-Start: dbus mountall
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: started dbus and started mountall
# Default-Stop: 2 3 4 5
# Short-Description: Start and stop noip
# Description: noip
### END INIT INFO

DAEMON=/usr/local/bin/noip2
NAME=noip2

test -x $DAEMON || exit 0

case "$1" in
    start)
    echo -n "Starting dynamic address update: "
    start-stop-daemon --start --exec $DAEMON
    echo "noip2."
    ;;
    stop)
    echo -n "Shutting down dynamic address update:"
    start-stop-daemon --stop --oknodo --retry 30 --exec $DAEMON
    echo "noip2."
    ;;

    restart)
    echo -n "Restarting dynamic address update: "
    start-stop-daemon --stop --oknodo --retry 30 --exec $DAEMON
    start-stop-daemon --start --exec $DAEMON
    echo "noip2."
    ;;

    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0
