#!/bin/sh
#Script de MAJ sécurité pour ITCPBX
#by Alexis LAUNAY
## MAJ Version 1.0.5 le 22/11/2013

# Vider les tables actuelles
#iptables -t filter -F

# Vider les règles personnelles
#iptables -t filter -X

# Interdire toute connexion entrante et sortante
iptables -t filter -P INPUT DROP
iptables -t filter -P FORWARD DROP
iptables -t filter -P OUTPUT ACCEPT

# Ne pas casser les connexions etablies
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

# Autoriser loopback
iptables -t filter -A INPUT -i lo -j ACCEPT
iptables -t filter -A OUTPUT -o lo -j ACCEPT

# ICMP (Ping)
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A OUTPUT -p icmp -j ACCEPT

# ---

# SSH In
iptables -t filter -A INPUT -p tcp --dport 6070 -j ACCEPT

# SSH Out
iptables -t filter -A OUTPUT -p tcp --dport 6070 -j ACCEPT

# DNS In/Out
iptables -t filter -A OUTPUT -p tcp --dport 53 -j ACCEPT
iptables -t filter -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 53 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 53 -j ACCEPT

# NTP Out
iptables -t filter -A OUTPUT -p udp --dport 123 -j ACCEPT

# HTTP + HTTPS Out
iptables -t filter -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 443 -j ACCEPT

# HTTP + HTTPS In
iptables -t filter -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 443 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 8443 -j ACCEPT

# Mail SMTP:25
iptables -t filter -A INPUT -p tcp --dport 25 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 25 -j ACCEPT

# Mail POP3:110
iptables -t filter -A INPUT -p tcp --dport 110 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 110 -j ACCEPT

# Mail IMAP:143
iptables -t filter -A INPUT -p tcp --dport 143 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 143 -j ACCEPT

# Mail POP3S:995
iptables -t filter -A INPUT -p tcp --dport 995 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 995 -j ACCEPT

# VPN

iptables -t filter -A OUTPUT -p tcp --dport 1723 -j ACCEPT
iptables -t filter -A OUTPUT -p udp --dport 1723 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 1723 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 1723 -j ACCEPT

iptables -t filter -A OUTPUT -p tcp --dport 500 -j ACCEPT
iptables -t filter -A OUTPUT -p udp --dport 500 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 500 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 500 -j ACCEPT

iptables -t filter -A OUTPUT -p tcp --dport 4500 -j ACCEPT
iptables -t filter -A OUTPUT -p udp --dport 4500 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 4500 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 4500 -j ACCEPT

iptables -t filter -A OUTPUT -p tcp --dport 1701 -j ACCEPT
iptables -t filter -A OUTPUT -p udp --dport 1701 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 1701 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 1701 -j ACCEPT

# Asterisk

iptables -t filter -A OUTPUT -p tcp --dport 5060 -j ACCEPT
iptables -t filter -A OUTPUT -p udp --dport 5060 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 5060 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 5060 -j ACCEPT

iptables -t filter -A OUTPUT -p tcp --dport 5061 -j ACCEPT
iptables -t filter -A OUTPUT -p udp --dport 5061 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 5061 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 5061 -j ACCEPT

iptables -t filter -A OUTPUT -p tcp --dport 10000:20000 -j ACCEPT
iptables -t filter -A OUTPUT -p udp --dport 10000:20000 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 10000:20000 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 10000:20000 -j ACCEPT

# Ban liste IP

iptables -I INPUT -s 54.200.235.239 -j DROP
iptables -I INPUT -s 198.7.59.151 -j DROP
iptables -I INPUT -s 198.27.68.179 -j DROP
iptables -I INPUT -s 176.31.123.59 -j DROP
iptables -I INPUT -s 188.165.252.218 -j DROP
iptables -I INPUT -s 176.31.65.141 -j DROP
iptables -I INPUT -s 37.8.45.62 -j DROP
iptables -I INPUT -s 82.205.11.32 -j DROP
iptables -I INPUT -s 162.13.4.193 -j DROP
iptables -I INPUT -s 178.162.205.235 -j DROP
iptables -I INPUT -s 198.27.68.179 -j DROP
iptables -I INPUT -s 162.13.4.193 -j DROP
iptables -I INPUT -s 176.31.65.141 -j DROP
iptables -I INPUT -s 193.111.136.1 -j DROP
iptables -I INPUT -s 178.162.205.216 -j DROP
iptables -I INPUT -s 176.31.0.0 -j DROP
iptables -I INPUT -s 85.195.73.75 -j DROP
iptables -I INPUT -s 178.162.0.0 -j DROP
iptables -I INPUT -s 198.27.0.0 -j DROP
iptables -I INPUT -s 216.155.138.218 -j DROP

#iptables -P INPUT DROP
#iptables -P OUTPUT ACCEPT

#iptables -P INPUT DROP
#iptables -P OUTPUT ACCEPT
iptables-save > /etc/iptables.up.rules
reboot
